#!/bin/bash

# This isn't created by me, but as there is no definitive copy out there, I decided to put it here.
# I did add a few features though, and make a sketchy window manager detector. It's disabled by default.
# If you want it anyways, and you don't use a desktop manager, uncomment the three lines labeled funWM

fun1(){
echo "$(whoami)@$(hostname)"
}
fun2(){
echo "CPU: $( cat /proc/cpuinfo | awk -F: '/name/ {print $2}' |\
 head -n 1 | sed -e 's/  */\ /g')" 
}
fun3() {
	echo "MEM:  $(free -m | awk '/cache:/ {print $3}')/$(free -m | awk '/Mem:/ {print $2}')MB"
}
fun4(){
	echo "GTK2: $(awk -F= '/gtk-theme-name/ {print $2}' ~/.gtkrc-2.0 | tr -d \")"
}
fun5(){
	echo "GTK3: $(awk -F= '/gtk-theme-name/ {print $2}' ~/.config/gtk-3.0/settings.ini)"
}
fun6(){
	echo "ICON: $(awk -F= '/gtk-icon-theme/	{print $2}' ~/.gtkrc-2.0 | tr -d \")"
}
fun7(){
	DISK="$(df -h --total 2> /dev/null | tail -1)"
	DISKS="$(echo $DISK | awk '{print $2}')"
	DISKF="$(echo $DISK | awk '{print $4}')"
	echo "DISK: $DISKF/$DISKS Available"
}
fun8(){
	echo "UPTM: 4:20"
}
fun9(){
	echo "PKGS: 420"
}
funMU(){
	mpc | grep -
}

#funWM(){
#	echo -e -n "WM:" && cat ~/.xinitrc | grep exec | sed s/"exec"/""/g   
#}

c="\e[1;32m"
b="\e[1;35m"
echo -e "
${c}                      .                         
${c}                      M
${c}                     dM
${c}                     MMr
${c}                    4MMML                  .   ${b}$(fun1)
${c}                    MMMMM.                xf   ${b}$(fun2)
${c}    .              \"MMMMM               .MM-   ${b}$(fun3)
${c}     Mh..          +MMMMMM            .MMMM    ${b}$(fun4)
${c}     .MMM.         .MMMMML.          MMMMMh    ${b}$(fun5)
${c}      )MMMh.        MMMMMM         MMMMMMM     ${b}$(fun6)
${c}       3MMMMx.     'MMMMMMf      xnMMMMMM\"     ${b}$(fun7)
${c}       '*MMMMM      MMMMMM.     nMMMMMMP\"      ${b}$(fun8)
${c}         *MMMMMx    \"MMMMM\"    .MMMMMMM=       ${b}$(fun9)
${c}          *MMMMMh   \"MMMMM\"   JMMMMMMP         ${b}PLAYING: $(funMU)
${c}            MMMMMM   3MMMM.  dMMMMMM           ${b}$(funWM)
${c}             MMMMMM  \"MMMM  .MMMMM(        .nnMP\"
${c} =..          *MMMMx  MMM\"  dMMMM\"    .nnMMMMM*
${c}   \"MMn...     'MMMMr 'MM   MMM\"   .nMMMMMMM*\"
${c}    \"4MMMMnn..   *MMM  MM  MMP\"  .dMMMMMMM\"\"
${c}      ^MMMMMMMMx.  *ML \"M .M*  .MMMMMM**\"  __ __ ___   ___
${c}         *PMMMMMMhn. *x > M  .MMMM**\"\"    / // /|__ \\ / __ \\
${c}            \"\"**MMMMhx/.h/ .=*\"          / // /___/ // / / /
${c}                     .3P\"%....          /__  __/ __// /_/ /
${c}                   nP\"     \"*MMnx         /_/ /____/\____/
"
