#!/bin/bash
# Downloads all the images in a 4chan thread
# Made by wallace.
# I'm not responsible if you end up deleting your filesystem.
# now u cant do that lol <3 butts
# u can overwrite files tho so heads up

dir="./"
echo -n "Enter full thread URL: "
read thread
echo "We are currently in $(pwd)."
echo -n "Enter download directory, default is current: "
read dir

if [ $dir == ""]
then
dir=$(pwd)
fi

mkdir "$dir"
cd "$dir"
wget -nd -nc -e robots=off --reject-regex [0-9]{13}[s]\. -rHD i.4cdn.org -A .jpg,.gif,.png,.webm $thread

echo "All actions completed sucessfully."
