#!/bin/bash
# For use with the Nichijou 2015 calendar available at https://mega.co.nz/#!zgQwVQbT!eZ85TJ5xZm1C0d_dqXDkl7R1wXRB8eyEJEKyilZA7ms

# Change this variable to the folder location
folder=$(whatever/wherever/whenever)

month=$(date +%m - %B)
day=$(date +%d)
feh -Z -g 328x525+950+125 $folder/$month/$day.jpg
